language: minimal

branches:
  only:
    - master

services:
  - docker

script:
  - docker build --tag elnebuloso/is-expired --pull --rm --no-cache --file Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elnebuloso/is-expired